# Generated by Django 5.0.3 on 2024-04-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_designation_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
