# Generated by Django 5.0.3 on 2024-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_of_joining_user_department_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
