# Generated by Django 5.0.3 on 2024-04-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
