# Generated by Django 5.0.3 on 2024-04-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_designation_employee copy'),
        ('users', '0002_user_dateofjoining_user_department_user_location'),
        ('users', '0013_user_dateofjoining_user_department_user_location'),
    ]

    operations = [
    ]
